version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Use relative path if the backend folder is inside the project root
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./resources/session_data:/app/resources/session_data  # Mounting a local folder to the container
    environment:
      - FLASK_ENV=production  # Set environment variables for the backend service

  frontend:
    build:
      context: ./frontend  # Assuming a frontend service; adjust path accordingly
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map port for the frontend service

